local:
  dialect: postgres
  datasource: host=localhost port=54321 user=postgres password=postgres dbname=db_local sslmode=disable
  dir: data/migrations
  table: migrations

prod:
  dialect: postgres
  datasource: host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} sslmode=${DB_SSL_MODE}
  dir: data/migrations
  table: migrations
