on: [pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    name: CI testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.3"

      - name: Init Test DB
        run: make setup && make init && make migrate-up
        env:
          GOPATH: "/home/runner/go"

      - name: Run Test Cases
        run: make test
